name: quiz_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  intl: ^0.19.0
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar: any
  feather_icons: ^1.2.0
  flutter_native_splash: 2.4.0
  percent_indicator: ^4.0.1
  loading_animation_widget: ^1.2.1
  im_stepper: ^1.0.1+1
  skeletonizer: ^1.1.1
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: '^0.13.1'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/launcher_icon_small.png'
  min_sdk_android: 21 
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/launcher_icon_small.png'
